version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Dublin
  open-pull-requests-limit: 10
  target-branch: develop
