version: 2
updates:

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Dublin
    open-pull-requests-limit: 10
    target-branch: develop

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Dublin
    open-pull-requests-limit: 10
    target-branch: develop
